services:
  - type: web
    name: api-gateway
    env: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=512
      - key: PORT
        value: 8080
