export const COUNTRIES = [
  { value: "", label: "Select your country" },
  { value: "US", label: "United States" },
  { value: "UK", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "IN", label: "India" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SG", label: "Singapore" },
  { value: "MY", label: "Malaysia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "JP", label: "Japan" },
  { value: "CN", label: "China" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "OTHER", label: "Other" },
];

export const SHOP_CATEGORIES = [
  { value: "", label: "Select a category" },
  { value: "Clothing & Apparel", label: "Clothing & Apparel" },
  { value: "Electronics & Gadgets", label: "Electronics & Gadgets" },
  { value: "Grocery & Supermarkets", label: "Grocery & Supermarkets" },
  { value: "Restaurants & Cafes", label: "Restaurants & Cafes" },
  { value: "Beauty & Personal Care", label: "Beauty & Personal Care" },
  { value: "Furniture & Home Decor", label: "Furniture & Home Decor" },
  { value: "Automotive & Accessories", label: "Automotive & Accessories" },
  { value: "Books & Stationery", label: "Books & Stationery" },
  { value: "Toys & Games", label: "Toys & Games" },
  { value: "Sports & Fitness", label: "Sports & Fitness" },
  { value: "Hardware & Tools", label: "Hardware & Tools" },
  { value: "Pet Supplies & Services", label: "Pet Supplies & Services" },
  { value: "Medical & Pharmacy", label: "Medical & Pharmacy" },
  { value: "Jewelry & Watches", label: "Jewelry & Watches" },
  { value: "Florists & Gift Shops", label: "Florists & Gift Shops" },
  { value: "Baby & Kids Store", label: "Baby & Kids Store" },
  { value: "Art & Craft Supplies", label: "Art & Craft Supplies" },
  { value: "Music Instruments & Stores", label: "Music Instruments & Stores" },
  {
    value: "Software & Technology Services",
    label: "Software & Technology Services",
  },
  { value: "Garden & Outdoor Equipment", label: "Garden & Outdoor Equipment" },
  { value: "Bakery & Confectionery", label: "Bakery & Confectionery" },
  { value: "Optical & Eyewear", label: "Optical & Eyewear" },
  {
    value: "Mobile Phones & Accessories",
    label: "Mobile Phones & Accessories",
  },
  {
    value: "Real Estate & Property Services",
    label: "Real Estate & Property Services",
  },
  { value: "Fitness & Wellness Centers", label: "Fitness & Wellness Centers" },
  { value: "Event Planning", label: "Event Planning" },
  { value: "Other", label: "Other" },
];
